name=TurbineFlowmeter
version=0.0.1
author=Facundo Checa
maintainer=Facundo Checa
sentence=Modbus turbine flowmeter sensor driver for Arduino.
paragraph=Provides reading functions for industrial Modbus RTU turbine flowmeter sensors.
category=Sensors
architectures=*
depends=ModbusMaster
url=https://github.com/FacundoCheca/TurbineFlowmeter
